DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255), ID_AUTHOR BIGINT, ID_GENRE BIGINT);

ALTER TABLE BOOKS ADD FOREIGN KEY (ID_AUTHOR) REFERENCES AUTHORS(ID);
ALTER TABLE BOOKS ADD FOREIGN KEY (ID_GENRE) REFERENCES AUTHORS(ID);
